---

- name: " AEM Dispatcher cache clear "
  hosts: "tag_Environment_{{Environment}}:&tag_Usage_{{Usage}}:&tag_Role_{{Role}}:&tag_AEMInstance_NO"
  user: ubuntu
  vars_files:
    - ../aem-variables.yml
    - ../aem-vault.yml

  tasks:
    
      - name: gather ec2 facts
        action: ec2_metadata_facts

      - name: " Delete cache inside dam/libs folder "
        file:
          path: "{{ aem_dispatcher_home_dir[ec2_tag_Role] }}/{{ item.value.dir_name }}/"
          state: absent
        with_dict: "{{ aem_dispatcher_cache_dirs }}"
