---

- name: " Install AEM packages "
  hosts: "tag_Environment_{{Environment}}:&tag_Usage_{{Usage}}:&tag_Role_{{Role}}"
  user: ubuntu
  vars_files:
    - aem-variables.yml
  tasks:


      - name: gather ec2 facts
        action: ec2_metadata_facts

      - name: " Get list of all packages"
        shell:
          ls -1 {{ deploy_local_folder_packages }}/{{ Environment }}/{{ Usage }}/{{ Role }}
        register: files
        delegate_to: localhost
      - debug: var=files.stdout_lines

      - name: " Install AEM packages "
        shell:
          curl -u 'admin:xt98m34p4kF4q$TB' -F force=true -F install=true -F file=@"{{ deploy_local_folder_packages }}/{{ Environment }}/{{ Usage }}/{{ ec2_tag_Role }}/{{ item }}" http://{{ ansible_ec2_local_ipv4 }}:{{ ec2_tag_AEMPort }}/crx/packmgr/service.jsp | tail -4 | grep 'code="200"'
        delegate_to: localhost
        with_items: "{{ files.stdout_lines }}"
        register: result
      - debug: var=result.stdout_lines
