---
      
    - name: Debug intersect
      debug:
        #msg: "{{ hostvars[groups['tag_Role_PublisherDispatcher'] | intersect(groups['tag_Environment_{{ env }}'])] }}"
        msg: "{{ hostvars[groups['env']] }}"
        #msg: "{{ groups['tag_Role_PublisherDispatcher'] }}"
    
    - name: AMI creation for PublisherDispatcher
      ec2_ami:
        instance_id: "{{ hostvars[groups['tag_Role_PublisherDispatcher'] | intersect(groups['tag_Environment_{{ env }}']) | first]['ec2_id'] }}"
        name: "{{ hostvars[groups['tag_Role_PublisherDispatcher'] | intersect(groups['tag_Environment_{{ env }}']) | first]['ec2_tag_Name'] }}-GoldBackup"
        no_reboot: yes
        region: us-west-2
        tags:
           Environment: "{{ env }}"
           Date: "{{ansible_date_time.date}}"

    - name: AMI creation for AuthorDispatcher
      ec2_ami:
        instance_id: "{{ hostvars[groups['tag_Role_AuthorDispatcher'] | intersect(groups['tag_Environment_{{ env }}']) | first]['ec2_id'] }}"
        name: "{{ hostvars[groups['tag_Role_AuthorDispatcher'] | intersect(groups['tag_Environment_{{ env }}']) | first]['ec2_tag_Name'] }}-GoldBackup"
        no_reboot: yes
        region: us-west-2
        tags:
           Environment: "{{ env }}"
           Date: "{{ansible_date_time.date}}"

    - name: AMI creation for Author
      ec2_ami:
        instance_id: "{{ hostvars[groups['tag_Role_Author'] | intersect(groups['tag_Environment_{{ env }}']) | first]['ec2_id'] }}"
        name: "{{ hostvars[groups['tag_Role_Author'] | intersect(groups['tag_Environment_{{ env }}']) | first]['ec2_tag_Name'] }}-GoldBackup"
        no_reboot: yes
        region: us-west-2
        tags:
           Environment: "{{ env }}"
           Date: "{{ansible_date_time.date}}"

    - name: AMI creation for Publisher
      ec2_ami:
        instance_id: "{{ hostvars[groups['tag_Role_Publisher']|intersect(groups['tag_Environment_{{env}}']) | first]['ec2_id'] }}"
        name: "{{ hostvars[groups['tag_Role_Publisher'] | intersect(groups['tag_Environment_{{ env }}']) | first]['ec2_tag_Name'] }}-GoldBackup"
        no_reboot: yes
        region: us-west-2
        tags:
           Environment: "{{ env }}"
           Date: "{{ansible_date_time.date}}"
