---
    - name: AMI creation for DEV
      ec2_ami:
        instance_id: "{{ hostvars[item]['ec2_id'] }}"
        name: "{{ hostvars[item]['ec2_tag_Name'] + '-' + fecha }}"
        no_reboot: yes
        region: us-west-2
        tags:
           Environment: "Dev"
           Gold: 'Yes'
      with_items: "{{ groups['tag_Environment_Dev'] }}"
