---
    - name: AMI creation for DEV
      ec2_ami:
        instance_id: "{{ hostvars[item]['ec2_id'] }}"
        name: "{{ hostvars[item]['ec2_tag_Name'] }}-GoldBackup"
        no_reboot: yes
        tags:
           Environment: "Dev"
           Date: "{{ansible_date_time.date}}"
      with_items: "{{ groups['tag_Environment_Dev'] }}"
