---

    - hosts: "tag_Environment_{{env}}:&tag_Role_{{group}}:&tag_Project_{{project}}"
      user: ubuntu

      tasks:
      - name: gather ec2 facts
        action: ec2_facts

      - name: security patching
        become: true
        apt:
          upgrade: dist
          update_cache: yes

      - name: reboot the server
        become: true
        command: /sbin/shutdown -r now

      - name: wait for host to restart
        local_action:
          module: wait_for
          host: "{{ ansible_ec2_local_ipv4 }}"
          port: 22
          delay: 1
          timeout: 300
