---

    - hosts: "tag_Environment_{{env}}:&tag_Role_Web"
      serial: 1
      user: ubuntu

      tasks:
      - name: gather ec2 facts
        action: ec2_facts

      - name: remove server out of the ELB
        local_action:
          module: ec2_elb
          instance_id: "{{ ansible_ec2_instance_id }}"
          region: "{{ ec2_region }}"
          state: absent

      - name: security patching
        become: true
        apt:
          upgrade: dist
          update_cache: yes

      - name: reboot the server
        become: true
        command: /sbin/shutdown -r now

      - name: wait for host to restart
        local_action:
          module: wait_for
          host: "{{ ansible_ec2_local_ipv4 }}"
          port: 22
          delay: 1
          timeout: 300

      - name: add servers back to the ELB
        local_action:
          module: ec2_elb
          instance_id: "{{ ansible_ec2_instance_id }}"
          region: "{{ ec2_region }}"
          ec2_elbs: "{{ elb_name }}"
          state: present
