---
    - name: AMI creation for PublisherDispatcher
        ec2_ami:
          instance_id: "{{ hostvars[groups['tag_Role_PublisherDispatcher'][0]]['ec2_id'] }}"
          name: "{{ hostvars[groups['tag_Role_PublisherDispatcher'][0]][ec2_tag_Name] }}-ansible_date_time.date"
          no_reboot: yes
          tags:
             Environment: "{{ env }}"

    - name: AMI creation for AuthorDispatcher
        ec2_ami:
          instance_id: "{{ hostvars[item]['ec2_id'] }}"
          name: "{{ hostvars[groups[item][ec2_tag_Name] }}-ansible_date_time.date"
          no_reboot: yes
          tags:
             Environment: "{{ env }}"
          with_items: "{{ groups['tag_Role_AuthorDispatcher'] }}"

    - name: AMI creation for Author
        ec2_ami:
          instance_id: "{{ hostvars[item]['ec2_id'] }}"
          name: "{{ hostvars[item][ec2_tag_Name] }}-ansible_date_time.date"
          no_reboot: yes
          tags:
             Environment: "{{ env }}"
          with_items: "{{ groups['tag_Role_Author'] }}"

    - name: AMI creation for Publisher
        ec2_ami:
          instance_id: "{{ hostvars[groups['tag_Role_Publisher'][0]]['ec2_id'] }}"
          name: "{{ hostvars[groups['tag_Role_Publisher'][0]][ec2_tag_Name] }}-ansible_date_time.date"
          no_reboot: yes
          tags:
             Environment: "{{ env }}"
